global:
  domain: argocd.sandbox.local

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    tls: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: !!str true
      nginx.ingress.kubernetes.io/ssl-passthrough: !!str true
      cert-manager.io/cluster-issuer: ca-issuer # Will create the certificate once Cert-Manager is deployed by ArgoCD.

configs:
  cm:
    exec.enabled: true