apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    labels:
      feature.node.kubernetes.io/port-mapping: !!str true
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
    extraMounts:
      - hostPath: w1
        containerPath: /data
  - role: worker
    extraMounts:
      - hostPath: w2
        containerPath: /data
  - role: worker
    extraMounts:
      - hostPath: w3
        containerPath: /data
