apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    labels:
      feature.node.kubernetes.io/port-mapping: !!str true

    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443

    extraMounts: &extraMounts
      - hostPath: shared
        containerPath: /data

  - role: worker
    extraMounts: *extraMounts
    
  - role: worker
    extraMounts: *extraMounts