apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-aoa
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: http://forgejo.sandbox.local:3000/administrator/exploration-gitops.git
        revision: HEAD
        directories:
          - path: kustomize/*
  template:
    metadata:
      name: "{{ .path.basename }}-kus"
      namespace: argocd
    spec:
      project: "default"
      source:
        repoURL: http://forgejo.sandbox.local:3000/administrator/exploration-gitops.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          enabled: true
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
